server:
  port: 8080
  contextPath: /

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 101MB
      file-size-threshold: 2KB
  jpa:
    open-in-view: true
    properties:
      hibernate:
    #        enable_lazy_load_no_trans: true
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/benchmark_hust?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connectionTimeout: 30000
      minimumIdle: 10
      maximumPoolSize: 50
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 10000
      poolName: benchmarkHiKariPool

logging:
  config: config/log4j2.yml

#logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql: trace

security.jwt.token.secret-key: secret-key

app:
  dir: .

token: dChR9i9y4CEeu0EmfynK2Nc6yuG2kYsPhENajjzT
csrf-token: eyJpdiI6IjZpQlFVWVp0WC9OVEdXTGFYbWxwcVE9PSIsInZhbHVlIjoiYUt0WUZFVnZQTVkxSW8rQzU1N1pXSVFXdndHdkpvK2IwaHBoVEFUaHlCYzBKSmRTYllERjhpOGxtQUhXdW1sc3o0NE5JK0RvUEpjdHBacS83K3JudHh1cHF5M1lQL1pJRmZNVEFKUWZmZHlnODd1RlhTNTg0czF0aFdKMFJ4SzciLCJtYWMiOiIzZGYzZjkyMmViZWI0OTA2OTdjODBmMTVkYWYzODM4YTY5MThlMmM3NzQwZGZkNTk0ZDg1Y2MzMzg2MmUwMTY0IiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6ImpENE10R0phTjQrWE9rU1hSRDM3RHc9PSIsInZhbHVlIjoibVI2aWZScldwVjQzWnhVMGpaZWVvSjNGVThWOGtMRFhJRG8vZTIzZlZ2TXp0bmhxOEsva2VRKzRRQ1JuQjlXeXQxYUJrVVh1N0VNK1VPRWRtTDltOXhESVVtekV0aXJvOXdxdXhqbFNkRVFxWUdwdVNlUXNoSSszOVZYMVA5dUIiLCJtYWMiOiJmZTVhZmI5MTJjNGYwZTM3YjU2MmYyMzZhZWEyYWEyMGEzZWQ5OGE0Zjc0ZjhjZDJhYjZjYzJjOWQyNzgxZmFiIiwidGFnIjoiIn0%3D;